### ISSUE TITLE
Typo on printed text of issues

### ISSUE THREAD

**Issue by PriyankaUofI** [ainspector/firefox-ainspector-wcag#58]
Test url - https://illinois.perfpro-hrnonline.com/

Please refer attached screenshots for the issue.
<img width="209" alt="AIIssue1" src="https://github.com/opena11y/ainspector-for-firefox/assets/84582289/4ed12a06-b6dd-4c4f-90d1-d2134fbec490">
<img width="205" alt="AIIssue2" src="https://github.com/opena11y/ainspector-for-firefox/assets/84582289/f01de1e4-191c-4bec-8a63-7b97ba8b4ae1">

**Comment by jongund** [comment]
Thank you for reporting this spelling problem, it will be fixed in the next release.

**Comment by jongund** [comment]
Fixed in release 1.99.6
